# Generated by Django 3.2.7 on 2021-09-15 15:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='couses',
            name='nisit',
            field=models.ManyToManyField(blank=True, related_name='couses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Nisit',
        ),
    ]
