# Generated by Django 3.2.7 on 2021-09-15 17:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20210915_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couses',
            name='nisit',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
