# Generated by Django 3.2.7 on 2021-09-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_couses_nisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='couses',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
